export const studies = [
  {
    id: 1,
    patientName: "John Doe",
    patientId: "P-1001",
    age: 45,
    gender: "M",
    modality: "CX",
    description: "Chest PA View",
    accession: "ACC-2024-001",
    assignedTo: "Dr. Smith",
    date: "2024-12-26 10:30",
    status: "Unreported",
    aiStatus: "With AI Detection",
    alerts: ["Critical"],
    locked: false,
    priority: "High"
  },
  {
    id: 2,
    patientName: "Jane Roe",
    patientId: "P-1002",
    age: 32,
    gender: "F",
    modality: "CT",
    description: "CT Brain Plain",
    accession: "ACC-2024-002",
    assignedTo: "DeepTek AI",
    date: "2024-12-26 09:45",
    status: "Saved",
    aiStatus: "With AI Detection",
    alerts: [],
    locked: true,
    priority: "Normal"
  },
  {
    id: 3,
    patientName: "Robert Brown",
    patientId: "P-1003",
    age: 67,
    gender: "M",
    modality: "MR",
    description: "MRI Lumbar Spine",
    accession: "ACC-2024-003",
    assignedTo: "-",
    date: "2024-12-25 16:20",
    status: "Unreported",
    aiStatus: "No AI Detection",
    alerts: [],
    locked: false,
    priority: "Normal"
  },
  {
    id: 4,
    patientName: "Emily Davis",
    patientId: "P-1004",
    age: 29,
    gender: "F",
    modality: "US",
    description: "USG Abdomen",
    accession: "ACC-2024-004",
    assignedTo: "Dr. A. Gupta",
    date: "2024-12-25 14:15",
    status: "Reported",
    aiStatus: "FO Detection Only",
    alerts: [],
    locked: false,
    priority: "Normal"
  },
  {
    id: 5,
    patientName: "Michael Wilson",
    patientId: "P-1005",
    age: 55,
    gender: "M",
    modality: "CR",
    description: "Knee AP/LAT",
    accession: "ACC-2024-005",
    assignedTo: "-",
    date: "2024-12-24 11:00",
    status: "QC Fix",
    aiStatus: "With AI Detection",
    alerts: ["Urgent"],
    locked: false,
    priority: "High"
  },
  {
    id: 6,
    patientName: "Sarah Miller",
    patientId: "P-1006",
    age: 41,
    gender: "F",
    modality: "CT",
    description: "CT Chest CECT",
    accession: "ACC-2024-006",
    assignedTo: "Dr. Smith",
    date: "2024-12-26 08:00",
    status: "Critical",
    aiStatus: "With AI Detection",
    alerts: ["Critical"],
    locked: false,
    priority: "Critical"
  },
  {
    id: 7,
    patientName: "David Lee",
    patientId: "P-1007",
    age: 72,
    gender: "M",
    modality: "DX",
    description: "Chest AP Bedside",
    accession: "ACC-2024-007",
    assignedTo: "-",
    date: "2024-12-26 10:55",
    status: "Unreported",
    aiStatus: "With AI Detection",
    alerts: [],
    locked: false,
    priority: "Normal"
  },
  {
    id: 8,
    patientName: "Olivia Taylor",
    patientId: "P-1008",
    age: 18,
    gender: "F",
    modality: "MR",
    description: "MRI Brain",
    accession: "ACC-2024-008",
    assignedTo: "Dr. Lee",
    date: "2024-12-23 09:30",
    status: "Reported",
    aiStatus: "No AI Detection",
    alerts: [],
    locked: false,
    priority: "Normal"
  },
  {
    id: 9,
    patientName: "James Anderson",
    patientId: "P-1009",
    age: 50,
    gender: "M",
    modality: "MG",
    description: "Mammography Bilateral",
    accession: "ACC-2024-009",
    assignedTo: "-",
    date: "2024-12-26 11:00",
    status: "Unreported",
    aiStatus: "With AI Detection",
    alerts: [],
    locked: false,
    priority: "Normal"
  },
  {
    id: 10,
    patientName: "Sophia Martinez",
    patientId: "P-1010",
    age: 60,
    gender: "F",
    modality: "CT",
    description: "CT Abdomen Pelvis",
    accession: "ACC-2024-010",
    assignedTo: "DeepTek AI",
    date: "2024-12-26 10:05",
    status: "Unreported",
    aiStatus: "With AI Detection",
    alerts: [],
    locked: false,
    priority: "Normal"
  },
];
